sudo: required

language: generic

services:
    - docker

before_install:
    - docker build -t rajeshbalan/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rajeshbalan/docker-react npm run test -- --coverage